project:
  type: website
  output-dir: docs

website:
  title: "Imad Dabbura"
  google-analytics: "UA-127825273-1"
  open-graph: true
  site-url: "https://imaddabbura.github.io/"
  repo-url: "https://github.com/imaddabbura/imaddabbura.github.io"
  repo-actions: [issue]
  favicon: images/favicon-32.png
  page-navigation: true
  reader-mode: true
  back-to-top-navigation: true
  page-footer:
    left: "Blog made with Quarto, by Imad Dabbura"
    right:
      - icon: twitter
        href: https://twitter.com/imadphd
      - icon: linkedin
        href: https://www.linkedin.com/in/imaddabbura/
      - icon: github
        href: https://github.com/imaddabbura
      - icon: medium
        href: https://medium.com/@ImadPhd
      - icon: envelope
        href: mailto:imad.dabbura@hotmail.com

  twitter-card:
    creator: "@imaddabbura"
    card-style: summary_large_image
  search:
    location: navbar
    type: overlay
    algolia:
      index-name: "my-website"
      application-id: "JZ1UWSSI1E"
      search-only-api-key: "c0b453df5f408deb4e62b620d94a91c6"
      show-logo: true
      analytics-events: true
  navbar:
    background: transparent
    foreground: dark
    logo: images/favicon-180.png
    left:
      - text: Blog
        file: posts.qmd
      - text: Paper Summaries
        file: papers-summaries.qmd
      - text: TIL
        file: til.qmd
      - text: Projects
        file: projects-index.qmd
      - text: DL Tips & Tricks
        file: dl-tips-tricks.qmd
      - text: More
        menu:
          - text: Library
            file: library.qmd
          - text: Notes
            file: misc-notes.qmd
          - text: Data Engineering
            file: data-eng-index.qmd
      - text: About
        file: about.qmd

    right:
      - icon: rss
        href: posts.xml
      - icon: github
        href: https://github.com/imaddabbura
editor-option:
  markdown:
    wrap: 72
filters:
  - filters/status-badge.lua
format:
  html:
    include-in-header:
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Petrona:ital,wght@0,400;0,500;0,600;0,700;1,400&family=Red+Hat+Text:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap" rel="stylesheet">
    include-after-body: _citation.html
    mermaid:
      theme: default
    code-overflow: wrap
    theme:
      light:
        - cosmo
        - assets/theme-light.scss
      dark:
        - cosmo
        - assets/theme-dark.scss
    lightbox: true
    code-link: true
comments:
  giscus:
    repo: imaddabbura/imaddabbura.github.io
