---
title: "ReAct: Synergizing Reasoning And Acting In Language Models"
date: 2024-07-10
categories:
  - LLM
  - NLP
  - DL
  - Agents
---
**[ReAct: Synergizing Reasoning And Acting In Language Models](https://arxiv.org/abs/2210.03629v3)**

- **Thesis**: Combine reasoning and acting to utilize the synergy between
  the two. With this approach, we can have reasoning traces as well as actions
  and handle exceptions when performing actions and interacting with the
environment
- **Methods**:
    - RaAct prompting template/technique that can be used for various
    problem-solving tasks
    - Augment context with `thought`, which LLM's reasoning over the current
    context. Context is nothing but a set of previous action/feedback pairs
- **Contribution**: 
    - ReAct framework, which is prompt-based technique to combine reasoning and
      acting
    - ReAct is easy to use, generalize to any problem domain, robust and
    outperform baseline, and finally aligned with humans
- **Takeaways**: There are great synergies between reasoning and acting. CoT is
  a black box that suffers from hallucination because it is not grounded with
external up-to-date relevant knowledge and is dependent on the model's internal
representation for reasoning ReAct augment this with actions by using tools and
external knowledge through actions and refine reasoning based on actions.
- **Improvements**:
    - Complex tasks may not see huge improvement with ReAct as its action space
      requires much more examples that can't be fit into context window. This
    problem is kind of resolved with increasing context window sizes of most
    LLMs

#nlp #llm #agents
