---
title: How to be a Better Programmer
date: 2022-09-15
categories: Programming
---
- Practice Drills:
    - Write your resume. List all the relevant skills that will still be used
      in 100 years. Rate yourself on each skill from 1-10.
        - Nice to have an up-to-date resume
        - Most likely you will find that math, computer science, writing, and
          people skills are for the most part timeless, universal skills. Most
          specific technologies, languages and protocols eventually expire, to
          be replaced by better alternatives
    - The knowledge of a technology or a framework will decrease in value if we
      don't keep it  current
    - Study by itself is not enough. We need to use what we learned and practice
      to make it stick
    - Make a list of programmers you admire and write down the few things that
      they seem to do well - things you wish you were better at
    - Mastering the tools of the trade is very important to make us effective
        - Make a list of the most common tools/programming languages you use and
          invest in learning them in depth
    - Read good and bad code and try to differentiate between both
    - Read known libraries' code to see their coding style/design
    - Work on open-source projects
    - Learn different programming languages
    - Understand the hardware effect on what you do
    - Write a blog that documents your learning
- Have a file (note) with the title "Things I don't know". This should include
  things important to your career that you either don't know or know very little.
- Not all experiences are created equal. Strive for mentorship and teams that
  help you learn more
- Focus your learning on three areas, in the following order:
    - Fundamentals
    - The latest version/feature of the stack(s) you use the most
    - In-demand tech that is backed by market leaders

#career-advice 