---
title: The Science of Setting and Achieving Goals 
date: 2022-01-26
categories: Personal Growth
---

## Introduction

Most people struggle in setting/executing/achieving goals due to many reasons that we are not going to cover in this document. I tried in this document to cover notes I've taken so far about the whole process of setting and achieving goals from neuroscience perspective. The psychological aspects are already covered in a lot of books about this topic, but rarely the neuroscience aspect is mentioned. I will keep updating this document in the event of learning/reading something new or from my own experience going the through process over the years. Please feel free to send your feedback with new resources/corrections so we can all benefit from it.

## Goals

Humans are particularly good at orienting the brain towards goals with different time trajectory: immediate goals, short-term goals, and long-term/lifetime goals. Also, humans are good at executing multiple goals at the same time.

**Neural circuit** is the brain areas that work together in concert when something happens. These areas work in sequence, each area is necessary in making an action happens but not sufficient. Therefore, all areas work together to lead to the occurrence of an action.

Brain circuits involved in all phases of goals (setting/executing/achieving) regardless of the kind of goals (small/big or short-term/long-term) are:

1. **Amygdala**: this area is responsible for fear and anxiety.
2. **Basal Ganglia**: it is responsible for action and it has two parts (circuits): 
    - One that generates **GO** (initiation of action)
    - One that generates the **NO GO** (prevention of action).
3. **Lateral Prefrontal Cortex**: it is involved with planning and thinking across different time scales.
4. **Orbito Prefrontal Cortex**: it is responsible for meshing some emotionality with current state of progress and comparing that emotionality with what it might be when we achieve the goal. Therefore, it is responsible of how we feel at present compared to how we would feel when reaching some predefined goal.

One part of the circuits will be involved in placing a value on the goal to determine whether it is worth pursuing. The other part is involved it taking the action; whether to do something or not do something, given the value of the goal.

**The Value of the goal is so critical in achieving the goal**. The reason behind this is that we have neuro-modulater system that governs setting/executing/achieving goals which is **Dopamine**. Dopamine is the currency by which we assess particular progress towards particular things of particular value. It is the way we use to assess value to our pursuit.

## Peripersonal Space vs. Extrapersonal Space

**Peripersonal Space** is the space within our body, the surface of our skin, and in our immediate environment. There are particular neurochemicals (such as ceretonine) and particular neuro-circuits that are responsible for consumatory behaviors such as using and consuming stuff with our immediate reach. Things like drinking from the cup next to us or feeling our internal body/breathing. We don't have to do much to consume/use stuff that are in our peripersonal space.

**Extrapersonal Space** is the space beyond the confinement of our reach in both *time* and *space* such as things in different room or other building or something in the future. The molecule that is most concerned with this is *dopamine*.

It is very important to understand both spaces to be efficient in setting/assessing/achieving our goals and be able to keep transitioning back and forth between those spaces:

1. We need to be able to understand our peripersonal space so that we can assess how feel and the progress we made towards goal(s) even if the goal has not been started yet or the stuff we're evaluating is in the future. Therefore, we use our peripersonal space to assess current feelings/state.
2. We need to be able to move to the extrapersonal space to move towards any goal.

## Visually Focusing on a Goal Line Improves Performance

- Multitasking is not good while doing goal-seeking activities that require focus and high level of cognition. However, it is good to do some form of multitasking before starting goal-seeking activities because it helps us be in the action mode which leads us to focus faster on the next task (due to adrenaline).

**Blood pressure:**

1. Systolic blood pressure (top number) which is what is measured when the heart contracts (beats).
2. Diastolic blood pressure (bottom number) which is what is measured between beats.

**There are two visual pathways:**

1. When we focus on something such as an object or simply a line regardless of how far it is. This helps with focus and increases attention/stress level. This would raise systolic blood pressure which also releases *adrenaline* by small amount as well as other stuff such as more Oxygen and fuel which in turn helps us get ready for action. As a result, visually focusing on one object helps prepare body and brain to move and be ready to take action.
2. When we are not focusing and just collecting wider view of the scene without necessarly focusing on any specific thing. This would reduce systolic blood pressure and any goal-seeking behaviors which also helps with relaxtion.

- Visually forcing ourselves to focus on a line or a dot (narrowing visual focus) on a wall or desk for 30-60 seconds will help us increase our level of cognitive attention and our ability to focus and stay focused. This is because most of out cognition follows our visual perception.
- Also, visually focusing on goal line will help us achieve the goal faster with less work (with the help of moving to the extrapersonal space).

## Tools

### Tool 1: Learn Faster with the 85% Rule

Neuroplasticity is how the brain changes connection between neurons that reflects new learnings. Mainly, it changes based on the errors we make while learning. If we don't make mistakes, there is nothing to learn and the brain wouldn't change anything since everything is working perfectly fine. Therefore, part of learning is making mistakes and learning from them. The brain would be in much better position after errors in terms of focus and ability to learn faster and absorb new material. As a result we should pursue errors not as the end goals but in an effort to make the brain more plastic.

But the big question is: What is the rate of errors we should look for to get the best learnings/plasticity?

- Too few errors don't result in learning because the brain is performing everything correctly.
- Too many errors result in frustration and not making progress because the task is much harder that the level we are at.

According to recent paper, it uses the 85% rule: we should target about 15% error rate to get the best of plasticity/learning and progress. The target should be around 15% since it is hard to measure the percise error rate; however, make sure to not exceed 20% or be below 10%.

### Tool 2: Use Focal Vision to Initiate Goal Pursuit

Given the importance of visually focusing on narrow/specific object, it is highly recommended to do it **30-60 seconds** right before starting the goal-seeking focused task. It is okay to blink while focuing on the object.

### Tool 3: Use Aged Self-Images to Self-Motivate

There is a phenomona called **delayed discounting**. In short, delayed discounting entails how we perceive future rewards for our immediate action. For example, most people struggle to save because; even though they acknowledge the importance of saving for retirement, they discount the rewards since it will be further in the future and tend to prefer immediate short-term rewards over long-term rewards. As a result, the future rewards need to be much bigger (or at least convince ourselve that it is much bigger) in order for our brain to be motivated to do it compared to other activities that have immediate/shorter-term rewards.

Due to the importance of visual system, labs at CMU did a study on two groups regarding the tendency of saving for retirement by showing one group actual image of themselves after 30-40 years and the other group just told about the need to save for retirement. They found that the group that saw their future images saved much higher than the other. As a result, it is good to use self-images before pursuing goals and always affirm the value of the goal and stay motivated.

### Tool 4: Visualizing Goals

It appears, according to multiple studies, that visualizing the goal and how it feels after achieving the goal has only effect at the start of the goal ONLY. After that, the effect starts to diminish until it becomes negligible. Therefore, it is only helpful in the process of setting the goals but not necessarly during execution or assessment.

### Tool 5: Visualizing Failure

Multiple studies showed that thinking about how things can fail and what would be the outcome of failing make us twice more likely to achieve the goal. When we imagine failure, there would be increase in the systolic blood pressure and readinness to perform actions which leads us to stay motivated and push extra hard to achieve those goals. The brain and body are much better at moving away from fearful things than moving towards things we like.

### Tool 6: Make Goals Moderately Lofty

If we classify goals into 3 categories: easy, moderate (hard but achievable), and very hard (impossible):

- Easy goals are too easy that they don't engage brain cicuits and body and doesn't change systolic blood pressure. So people are more likely to drop those goals
- Hard (impossible) goals also get dropped due to the same reasons the easy goals get dropped but in the opposite direction (crash systolic blood pressure)
- Moderate goals; goals that are hard enough but reachable, are much more likely to be achieved and engage brain circuits and body. Studies have shown that such goals are at least twice as likely to pursued and achieved than other goals.

Therefore, set goals that are moderate-to-hard in order to increase the likelihood of achieving them. Not too easy and not too hard goals.

### Tool 7: Avoid Goal Distraction; Focus on 1-2 Major Goals Per Year

When we our visual system has so many things in the environment to look at, this will drift our attention from what we planned to do and end up doing completely different things that may even contradict what we had in mind and planned to do. Department stores figured this out by stocking their shelved with so many things and varieties that make people much more likely to buy stuff that never thought about or even need. Therefore, by having sparse space help our brain and visual system stay focued and do what we planned to do. Therefore, 2 (or max 3) major goals per year are more than enough for most people.

### Tool 8: Ensure Specificity of Goals, Weekly Assessment

We need to be specific about what success would look like and have an action plan of what it takes to achieve the goal. In other words, there needs to be specific steps that have to be performed to achieve the goal so it makes it easier on the brain to know what to do next and reduce the amount of will-power needed to start goal-seeking activities. It also helps us in measuring progress and updating action plan.

It is highly recommended to have a weekly assessment to measure what has been done in the previous week and what should be done in the coming week by uodate the action plan. The assessment should be written and advisable to have specific day/time every week dedicated to this exercise where the focus will be only on the assessment and revisiting goals/action plans.

### Tool 9: Space-Time Bridging

1. Close your eyes for 3 shorth breaths and focus on what is happening inside your body and void any external distraction
2. Open your eyes and look at something on the skin of your body for short breaths. The attention should be 90% on the internal body and 10% on the visual cognition of the skin part we're looking at.
3. Look at something 5-15 ft away for 3 short breaths. The focus would be 90% on the object we're looking at and 10% on our internal body.
4. Look at something very far for 3 short breaths. The focus should be around 99% on the object we're looking at and 1% on our internal body.
5. Expand visual horizon to include everything in the horizon for 3 shorth breaths. The focus should be 100% on the external (extrapersonal) space.

Repeat the above steps 2-3 times once daily. This should teach our brain system related to goal setting/assessment/execution to adjust and move between different time-frames and allow us to concieve the pursuit of different goals over different periods of time

## Dopamine

**Dopamine** is thought as the molecule for pleasure and reward. However, it is actually for motivation. Therefore, it affects the motivation of performing the actual steps that lead to pleasure/rewards.

Dopamine reward prediction error:
- If something positive happens that we didn't expect -> A lot of dopamine is released
- If we anticipate something positive to happen -> Dopamine is release during anticipation period (before receiving the reward) and small release happen after recieving the reward. The releases are not as much as if something positive was not expected.
- If we anticipate something positive to happen but it didn't happen -> Dopamine is released during the waiting (anticipation) period but then dropped below initial level when it doesn't happen.

Our brain has the ability to change the nature of the same behavior from positive to negative and vise versa. For example, if you voluntarily exercise vs. someone force you to exercise. It is the same action but, according to multiple studies, people (or rats) who were forced to exercise generated negative results including blood pressure and other health metrics while others who exercised voluntarily generated positive metrics.

As a result, we should pick a milestone (assessment) that we can maintain consistently with the reward schedule (cognitive rewards). Weekly assessment is perfect: it is not too granular neither it is too infrequent. The reward can be as simple as checking a box that certain tasks have been achieved and acknowledging that we did it and we are on the right track. This helps us stay motivated and ready to pursue the goal.

There are things that help increase the release of dopamine such as: cold shower or cold water exposure which has been shown to increase the release of dopamin by 2.5x or consumption of caffiene that increases the dopamin receptors which make dopamin floating around more effective in activating motivational state.

## Resources

- [The 85% Rule for Optimal Learning](https://www.nature.com/articles/s41467-019-12552-4)
- [Effects of Narrowing Visual Attention on Goal Pursuit Behavior](https://journals.sagepub.com/doi/10.1177/0146167219861438)
- [Huberman Lab Podcast](https://www.youtube.com/c/AndrewHubermanLab/videos)---
