---
title: Notes on Shipping Projects
date: 2024-08-01
categories: Personal Growth
---
- Writing for specific audience about specific topic is much easier and faster to deliver
- Set a deadline and ship whatever done by the time you reach the deadline regardless of what has been done or its quality. View deadline as a challenge.
- Work backwards:
	- What’s the end result look like, exactly?
	- How many features?
	- What is absolutely required, what’s nice to have?
	- How perfect does it have to be?
	- How long will each of these take?
	- What has to come first?
	- What do I need to prepare?
	- How long will that take?
	- What do I need to find out?
	- How long will that take?
	- How much, or how little, defines success? And who controls that?
- Break it into pieces. For projects, break it into separate components and do deep work/focused sessions to finish each component separately. This has the advantage of keeping motivation high as a result of the feeling of accomplishments
- Get super clear on the details of every stage to help you know when you're done
- Start small. This will give you an idea what it would take to build the project you're aiming for.
- Track your progress using tools such as `Trello`. Keep the *completed tasks* visible to get the satisfaction from accomplishing tasks always visible.
	- Visible progress is a great motivator
	- Emotional management makes a big difference during the different stages of the project
- Don't reinvent the wheel. Use existing tools/libraries that help you deliver the project faster and get customer feedback. You can always come back later to improve the tools or build your own from scratch if there is a need for that
- Every version should be better. This means you don't have to ship perfect product because future iterations will always improve different aspects of the product
- Define success criteria to ship the first version of the project
- Research and do literature review before starting the project. This would help determine the tools to use, structure of the project and its components, etc. and the rest would be left for implementation/execution
- Write down the must-haves and nice-to-have features
- Mistakes can happen after shipping the product. Don't take it personally and just try to fix them
- Shipping now is much better than shipping perfect project later. You learn much more from trial and error and faster iterations than perfect project

#productivity #career-advice 
