---
title: Notes From Random Readings in Personal Growth
date: 2022-12-25
categories: Personal Growth
---

- Do not end the week with nothing:
    1. Prefer Working On Things You Can Show. If you can not show your work, then work on side projects.
    2. Prefer To Work Where People Can See you.
    3. Prefer To Work On Things You can Keep. This means that sometimes getting your code/project into Github and letting people use it may not be the best strategy. The reason is that nobody will attribute your code that was used in bigger projects that are built by different people. However, when you build a package/website around the project, people have no choice but to give you credit and you will start getting noticed in the industry.
    4. Consumption Is Sometimes Valuable, But Creation Moves You Forward. JUST DO NOT END THE WEEK WITH NOTHING!
- I am in charge of my life, so I better lead it and live it the way I want.
- Begin with the end in mind.
- Use time blocking for scheduling and not the bullet to-do list. This will help us put regular tasks on autopilot scheduling where we just perform the task without thinking about whether we should do it now or later. The non-regular tasks will be scheduled.
- First things first. Those are tasks that help us achieve our goals and get where we want to be. Small things such as non-regular tasks can be done in the gaps between the important tasks.
- Communicate the value you create so people can know what you did.
- Develop content that can be consumed for multiple purposes. For example, if at work we need to research some ideas, write a blog about them and then refer people to it from the company.
- Create the content on your domain (website) so you can own it and get recognized. This will also help build my brand.
- Be consistent in developing useful content. This will make people take you more seriously and want to read what you produce.
- Increase the impact of your value. I can write a blog post or record a video about problems we're having at work and publish that online. Then I can refer co-workers to that when they have questions. I can also create libraries and open source them that are mainly driven by my job. This way, I will be reaping the benefits of sharing knowledge online, solving my problems at work, and eventually becoming more recognized. All of this can happen while I am on the clock doing my job.
- Have an investment mindset, not an hourly mindset: This means investing in skills that lead to return in the long term and keep growing, DO NOT prefer the fixed return that will pay you the same amount of money in exchange for time. Therefore, prioritize your work and learning to the ones that have a long-term effect even if it may not have a great return in the beginning.
- Wealth is about having options, not about having money. With money, we can buy time by paying people to do stuff for us that is not worth our time such as mowing our lawn.
- Three practices to become an outlier:
  - Command your time: Build a system that consists of useful habits:
    1. We have different burners: Family, Religion, Job, Self Development, Health, Recreation, and Civic. So optimize for the ones that add the most value given your current situation. Just keep in mind that it may affect other burners and you should not stress about it because you only have 24 hours a day.
    2. Do multiple things at the same time that doesn't require much focus such as a family call or listening to a podcast while working out or driving.
    3. Try changing meeting schedules so they don't take the most productive time of day plus put them together so you don't have much of a context switch because we need a big chunk of time to do development work and have deep work sessions.
  - Hack your image: Perception is reality. It is very important how people perceive you. It is also very important to let people know the value you created and communicate that eloquently.
    - Developer Image: You can strive to have three of them but u can pick only two.
      - Easy to work with
      - Deliver on time
      - Do great work
  - Own your trajectory
    - Think as if money is not an object.
    - The key to SUCCESS is to learn to teach yourself more efficiently than any institution can.
    - Scale yourself.
    - Your Luck Surface Area is directly proportional to the degree to which you do something you're passionate about combined with the total number of people to whom this is effectively communicated. Therefore, **Luck = Doing * Telling**.
- IF YOU WANT TO BE AN ANOMALY, YOU'VE GOT TO ACT LIKE ONE.
- Stay on your lane and DO NOT start dabbling into different technologies/things that may be cool but do not help you achieve your mission. Avoid the tendency of trying everything new and/or looking cool if it does not fit into your plan.
- Caring cycle: Caring -> Dedication -> Mastery -> Trust -> Autonomy.
- Focus on JUST-IN-TIME learning, not JUST-IN-CASE.
- Systems are better than goals:
  - Goals have an endpoint. Systems don't.
  - Goals require willpower. Systems don't.
  - Goals are all or nothing. Systems aren't.
  - Goals limit upside. Systems don't.
- Want SUCCESS?
  - Define it
  - Figure out the price
  - Pay it
- “Your outcomes are a lagging measure of your habits. Your net worth is a lagging measure of your financial habits. Your weight is a lagging measure of your eating habits. Your knowledge is a lagging measure of your learning habits. Your clutter is a lagging measure of your cleaning habits.
You get what you repeat.”
- In brief, sleep produces complex neurochemical baths that improve our brains in various ways. And it “restocks the armory of our immune system, helping fight malignancy, preventing infection, and warding off all manner of sickness.” In other words, sleep greatly enhances our evolutionary fitness—just in ways we can’t see.
- Think of time as money. When deciding between things, think in terms of how much is your hourly rate worth and this will give an idea if the activity will be worth it or not.
- You have to act as a Senior before you become a Senior. This means you have to have enough required skills and accomplishments and market yourself as meeting those requirements. Main qualities of a Senior:
  - Communication
  - Seeing the big picture
  - Impact on team's work
  - Mentoring
  - Working across teams
  - Solid technical expertise (especially fundamentals)
- Most of the knowledge is **tacit knowledge**; knowledge that is gained by experience and not written down and can't be acquired by reading. Therefore, write down all the learnings (such as TIL or blog posts) so they can stick more and be shareable with others which also helps market yourself online.
- Dreyfus Model of Skill Acquisition: Novice -> Advanced beginner -> Competent -> Proficient -> Expert.
- It is very helpful to write down:
  - Things that I like working on
  - Who I like to work with
  - What problems excite me and get me out of my bed
- It is recommended to position myself 6-12 months before the big move after deciding what I want.
- Spend time learning to be a good storyteller because most senior jobs ask about previous scenarios and want to see your way of thinking and handling complex problems and what value did u add to your team.
- Practicing also allows you to recall from the past when tackling new problems instead of thinking about how to solve every problem because most likely you failed before and learned a few tips along the way that become muscle memory that you can use in the future.
- Productive meditation: Needs to let your brain deep dive into one specific problem. Every time you notice that your brain starts thinking about something else, bring it back to the same problem you want to think about.
- Do not focus on specific jobs when planning your career. Instead, focus on job attributes that make sense and you like and acquire career capital that would let you be in those jobs.
- Don't do invisible work:
    - As time goes by, you will remember less of what you did. Your boss will even
      remember less than what you remember for the same time period.
    - Since performance reviews and bonuses are based on what your boss and others
      remember of what you did:
      - You need to track all the tihings you do on a weekly basis
      - Use a tool that store your work
      - Tell people about it
    - Tools:
        - Brag docs: polished accomplishments that can be shared with your manager
          about all the progress/work you did. Check Juila Evans template
        - Simple text file which has one liner for all activities
        - Write blog posts about all important work
        - Written is better than verbal, and formal is better than informal
- It is not what you do, it is what you do consistently that determines your destiny
- knowledge and productivity are like compound interest
- If what you are doing is not important, and if you don't think it is going to
  lead to something important, why are you working on it!!!
    - What are the important problems in my field?
    - What important problems are you working on?
- Where is my field going? Where were the opportunities? What are the important
  things to do?
